### ISSUE TITLE
fail to create config and credentials file with root

### ISSUE THREAD

**Issue by deconya** [badpacketsllc/ansible-aws_cli#1]
Hi
Im checking to use this role using playbook to register content. Mi playbook is:

```yaml
---
- hosts: "test"
  become: yes

  vars:
      profiles:
        - ireland:
            region: eu-west-1
            output: text
            aws_access_key_id: MysecretKEY
            aws_secret_access_key: Mysecretpassword
        -  brazil:
            region: sa-east-1
            output: text
            aws_access_key_id: MysecretKEY
            aws_secret_access_key:  Mysecretpassword
  roles:
    - badpacketsllc.aws_cli
```

If I execute all appears nice but inside config and credentials file only appear 

```shell
# Ansible managed
```

Im executing how ec2-user and Im looking to create files inside root directory

**Comment by woodrad** [comment]
Thanks for using our Ansible role!

I think the root cause of your issue is missing `name:` before the name of your profiles. Try the play below and tell me if it works for you.

```yaml
---
- hosts: "test"
  become: yes

  vars:
    profiles:
      - name: ireland
        region: eu-west-1
        output: text
        aws_access_key_id: AKIAIOSDNKOW7EXAMPLE
        aws_secret_access_key: wJalrXUtnFEMI/F3GXCLG/bPxRfiCYEXAMPLEKEY
      - name: brazil
        region: sa-east-1
        output: text
        aws_access_key_id: AKIAIOSDNKOW7EXAMPLE
        aws_secret_access_key: wJalrXUtnFEMI/F3GXCLG/bPxRfiCYEXAMPLEKEY
  roles:
    - badpacketsllc.aws_cli
```

I used Amazon Linux on a t3.nano to test. Hopefully this is close enough to your environment that the playbook above does the trick. 

Let me know if this fixes the problem you've encountered.

**Comment by deconya** [comment]
Hi
Now only fails when create credential file, but config seems to be nice If I create default part produce error:

```yaml
vars:
       profiles:
         - default:
           region: eu-west-1
           output: text
           access_key_id: MysecretKEY
           secret_access_key: Mysecretpassword
         - name: ireland
           region: eu-west-1
           output: text
           access_key_id: MysecretKEY
           secret_access_key: Mysecretpassword
         - name: brazil
           region: sa-east-1
           output: text
           access_key_id: MysecretKEY
           secret_access_key: Mysecretpassword
```
```
 FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'name'"}
```

**Comment by woodrad** [comment]
There are two bugs in the snippet you provided.

1. The `name` key is required and
2. `access_key_id` and `secret_access_key`should be ` aws_access_key_id` and `aws_secret_access_key`

Try something like this and let me know if it works for you.

```yaml
---
- hosts: all
  become: yes

  vars:
    profiles:
      - name: default
        region: eu-west-1
        output: text
        aws_access_key_id: MysecretKEY
        aws_secret_access_key: Mysecretpassword
      - name: ireland
        region: eu-west-1
        output: text
        aws_access_key_id: MysecretKEY
        aws_secret_access_key: Mysecretpassword
      - name: brazil
        region: sa-east-1
        output: text
        aws_access_key_id: MysecretKEY
        aws_secret_access_key: Mysecretpassword
  roles:
    - badpacketsllc.aws_cli
```

I just noticed that the example in the readme does not indicate the `name` key is needed. I'll fix that.
