### ISSUE TITLE
Install awscli is not working in Ubuntu 18 at least

### ISSUE THREAD

**Issue by tom10271** [badpacketsllc/ansible-aws_cli#19]
It seems I need to update apt manually first

**Comment by woodrad** [comment]
Could you post an example of the playbook you're using and the error output from `ansible-playbook`? You might want to try something like this before attempting to run `aws_cli`:

```yaml
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
```
